### ISSUE TITLE
Can’t checkout plugin without a plugins-path

### ISSUE THREAD

**Issue by prijupaul** [hasura/smooth-checkout-buildkite-plugin#26]
Hi,

I have added the steps, 

```
steps:
  - command: echo "Check out signing repo"
    plugins:
      - hasura/smooth-checkout#v3.1.0:
          repos:
            - config:
                - url: git@github.xxxxxxxxxx.com.au:Digital/ios-match-certificates.git
```

however, i get “:rotating_light: Error: Failed to checkout plugin smooth-checkout: Can’t checkout plugin without a plugins-path”

Do I need to add the plugins-path after "hasura/smooth-checkout#v3.1.0:"
