### ISSUE TITLE
Support Checking out code

### ISSUE THREAD

**Issue by scriptnull** [hasura/smooth-checkout-buildkite-plugin#4]
We will introduce configurations needed for checking out the code for a ref

A ref could be
- a branch name
- a commit sha
- a git tag

```yml
steps:
  - command: echo "Skips checking out Git project in checkout" 
    plugins:
      - hasura/smooth-checkout#v1.0.0:
          clone_url: $BUILDKITE_REPO
          ref: $BUILDKITE_TAG
```
